[package]
name = "rust-sig"
version = "0.1.0"
edition = "2024"

[dependencies]
concat-idents = "1.1.5"
http-body-util = "0.1.5"
futures-channel = "*"
url = "2"

reqwest = { version = "=0.12.26", optional = true }
hyper = { version = "=1.11.0", optional = true }
http = { version = "=1.5.0", optional = true }
# hyper-rustls = { version = "=0.26.0", optional = true }

[[bin]]
name = "rust-sig"
path = "main.rs"

[features]
feat-reqwest = ["dep:reqwest"]
feat-hyper = ["dep:hyper"]
feat-http = ["dep:http"]
# feat-hyper-rustls = ["dep:hyper-rustls"]

default = ["feat-http"]
