name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false # Allows jobs to fail independently.
      matrix:
        build-env:
          - os: windows-latest
            arch: i686-pc-windows-gnu
          - os: windows-latest
            arch: i686-pc-windows-gnullvm
          - os: windows-latest
            arch: i686-pc-windows-msvc
          - os: windows-latest
            arch: i686-uwp-windows-gnu
          - os: windows-latest
            arch: i686-uwp-windows-msvc
          - os: windows-latest
            arch: i686-win7-windows-gnu
          - os: windows-latest
            arch: i686-win7-windows-msvc
          - os: windows-latest
            arch: x86_64-pc-windows-gnu
          - os: windows-latest
            arch: x86_64-pc-windows-gnullvm
          - os: windows-latest
            arch: x86_64-pc-windows-msvc
          - os: windows-latest
            arch: x86_64-uwp-windows-gnu
          - os: windows-latest
            arch: x86_64-uwp-windows-msvc
          - os: windows-latest
            arch: x86_64-win7-windows-gnu
          - os: windows-latest
            arch: x86_64-win7-windows-msvc

          - os: ubuntu-latest
            arch: i686-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnuasan
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnumsan
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnutsan
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnux32

        dependency-to-test:
          - reqwest


    runs-on: ${{ matrix.build-env.os }}

    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Out
      uses: actions/checkout@v4

    - name: Collect Versions
      run: |
        curl https://crates.io/api/v1/crates/reqwest -H 'User-Agent: @Windows81 on GitHub' \
        | jq -r '.versions|reverse[].num' \
        | tee "${{ runner.temp }}/versions.txt"

    - name: Build
      run: |
        while read -r line; do
          cargo add "${{ matrix.dependency-to-test }}@$line"
          cargo build --target ${{ matrix.build-env.arch }} --features dep_${{ matrix.dependency-to-test }} --verbose --release -- -C opt-level=3 -C link-dead-code=y -C panic=abort
          cargo run >results/${{ matrix.build-env.arch }}-${{ matrix.dependency-to-test }}-$line.txt
        done <${{ runner.temp }}/versions.txt

    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        add: results
        message: 'Update latest prices.'
